CREATE TABLE students (
    id INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    full_name VARCHAR(20) NOT NULL,
    phone_number VARCHAR(20) NOT NULL,
   email VARCHAR(20) NOT NULL,
   gender VARCHAR(100) NOT NULL
);

ALTER TABLE students
ADD COLUMN admission_number VARCHAR(50) NOT NULL,
ADD COLUMN course VARCHAR(50) NOT NULL;